// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: stp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Introduce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Padding       []byte                 `protobuf:"bytes,1,opt,name=padding,proto3" json:"padding,omitempty"`
	Public        []byte                 `protobuf:"bytes,2,opt,name=Public,proto3" json:"Public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Introduce) Reset() {
	*x = Introduce{}
	mi := &file_stp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Introduce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Introduce) ProtoMessage() {}

func (x *Introduce) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Introduce.ProtoReflect.Descriptor instead.
func (*Introduce) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{0}
}

func (x *Introduce) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *Introduce) GetPublic() []byte {
	if x != nil {
		return x.Public
	}
	return nil
}

type SignedTransport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,3,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Padding       []byte                 `protobuf:"bytes,4,opt,name=padding,proto3" json:"padding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransport) Reset() {
	*x = SignedTransport{}
	mi := &file_stp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransport) ProtoMessage() {}

func (x *SignedTransport) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransport.ProtoReflect.Descriptor instead.
func (*SignedTransport) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{1}
}

func (x *SignedTransport) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignedTransport) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedTransport) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SignedTransport) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_stp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Padding       []byte                 `protobuf:"bytes,1,opt,name=padding,proto3" json:"padding,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	SessionID     *string                `protobuf:"bytes,4,opt,name=SessionID,proto3,oneof" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_stp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{3}
}

func (x *Handshake) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *Handshake) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Handshake) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Handshake) GetSessionID() string {
	if x != nil && x.SessionID != nil {
		return *x.SessionID
	}
	return ""
}

var File_stp_proto protoreflect.FileDescriptor

const file_stp_proto_rawDesc = "" +
	"\n" +
	"\tstp.proto\x12\x03box\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\tIntroduce\x12\x18\n" +
	"\apadding\x18\x01 \x01(\fR\apadding\x12\x16\n" +
	"\x06Public\x18\x02 \x01(\fR\x06Public\"\x88\x01\n" +
	"\x0fSignedTransport\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12\x1c\n" +
	"\tSignature\x18\x02 \x01(\fR\tSignature\x12)\n" +
	"\bMetadata\x18\x03 \x01(\v2\r.box.MetadataR\bMetadata\x12\x18\n" +
	"\apadding\x18\x04 \x01(\fR\apadding\"`\n" +
	"\bMetadata\x12\x1a\n" +
	"\bSequence\x18\x01 \x01(\x04R\bSequence\x128\n" +
	"\tTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\"~\n" +
	"\tHandshake\x12\x18\n" +
	"\apadding\x18\x01 \x01(\fR\apadding\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\fR\x03Key\x12\x14\n" +
	"\x05Nonce\x18\x03 \x01(\fR\x05Nonce\x12!\n" +
	"\tSessionID\x18\x04 \x01(\tH\x00R\tSessionID\x88\x01\x01B\f\n" +
	"\n" +
	"_SessionIDB\x06Z\x04./pbb\x06proto3"

var (
	file_stp_proto_rawDescOnce sync.Once
	file_stp_proto_rawDescData []byte
)

func file_stp_proto_rawDescGZIP() []byte {
	file_stp_proto_rawDescOnce.Do(func() {
		file_stp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stp_proto_rawDesc), len(file_stp_proto_rawDesc)))
	})
	return file_stp_proto_rawDescData
}

var file_stp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stp_proto_goTypes = []any{
	(*Introduce)(nil),             // 0: box.Introduce
	(*SignedTransport)(nil),       // 1: box.SignedTransport
	(*Metadata)(nil),              // 2: box.Metadata
	(*Handshake)(nil),             // 3: box.Handshake
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_stp_proto_depIdxs = []int32{
	2, // 0: box.SignedTransport.Metadata:type_name -> box.Metadata
	4, // 1: box.Metadata.Timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stp_proto_init() }
func file_stp_proto_init() {
	if File_stp_proto != nil {
		return
	}
	file_stp_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stp_proto_rawDesc), len(file_stp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stp_proto_goTypes,
		DependencyIndexes: file_stp_proto_depIdxs,
		MessageInfos:      file_stp_proto_msgTypes,
	}.Build()
	File_stp_proto = out.File
	file_stp_proto_goTypes = nil
	file_stp_proto_depIdxs = nil
}
