// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: stp.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedTransport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Context       *TransportContext      `protobuf:"bytes,3,opt,name=Context,proto3,oneof" json:"Context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedTransport) Reset() {
	*x = SignedTransport{}
	mi := &file_stp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedTransport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTransport) ProtoMessage() {}

func (x *SignedTransport) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTransport.ProtoReflect.Descriptor instead.
func (*SignedTransport) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{0}
}

func (x *SignedTransport) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SignedTransport) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedTransport) GetContext() *TransportContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type TransportContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportContext) Reset() {
	*x = TransportContext{}
	mi := &file_stp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportContext) ProtoMessage() {}

func (x *TransportContext) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportContext.ProtoReflect.Descriptor instead.
func (*TransportContext) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{1}
}

type Introduce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Public        []byte                 `protobuf:"bytes,1,opt,name=Public,proto3" json:"Public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Introduce) Reset() {
	*x = Introduce{}
	mi := &file_stp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Introduce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Introduce) ProtoMessage() {}

func (x *Introduce) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Introduce.ProtoReflect.Descriptor instead.
func (*Introduce) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{2}
}

func (x *Introduce) GetPublic() []byte {
	if x != nil {
		return x.Public
	}
	return nil
}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Salt          []byte                 `protobuf:"bytes,2,opt,name=Salt,proto3" json:"Salt,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Opts          *HandshakeOptions      `protobuf:"bytes,4,opt,name=Opts,proto3,oneof" json:"Opts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_stp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{3}
}

func (x *Handshake) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Handshake) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *Handshake) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Handshake) GetOpts() *HandshakeOptions {
	if x != nil {
		return x.Opts
	}
	return nil
}

type HandshakeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeOptions) Reset() {
	*x = HandshakeOptions{}
	mi := &file_stp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeOptions) ProtoMessage() {}

func (x *HandshakeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeOptions.ProtoReflect.Descriptor instead.
func (*HandshakeOptions) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{4}
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []byte                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_stp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{5}
}

func (x *Conversation) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Conversation) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_stp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_stp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_stp_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_stp_proto protoreflect.FileDescriptor

const file_stp_proto_rawDesc = "" +
	"\n" +
	"\tstp.proto\x12\x03box\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"\x0fSignedTransport\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12\x1c\n" +
	"\tSignature\x18\x02 \x01(\fR\tSignature\x124\n" +
	"\aContext\x18\x03 \x01(\v2\x15.box.TransportContextH\x00R\aContext\x88\x01\x01B\n" +
	"\n" +
	"\b_Context\"\x12\n" +
	"\x10TransportContext\"#\n" +
	"\tIntroduce\x12\x16\n" +
	"\x06Public\x18\x01 \x01(\fR\x06Public\"\x80\x01\n" +
	"\tHandshake\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\fR\x03Key\x12\x12\n" +
	"\x04Salt\x18\x02 \x01(\fR\x04Salt\x12\x14\n" +
	"\x05Nonce\x18\x03 \x01(\fR\x05Nonce\x12.\n" +
	"\x04Opts\x18\x04 \x01(\v2\x15.box.HandshakeOptionsH\x00R\x04Opts\x88\x01\x01B\a\n" +
	"\x05_Opts\"\x12\n" +
	"\x10HandshakeOptions\"S\n" +
	"\fConversation\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\fR\aMessage\x12)\n" +
	"\bMetadata\x18\x02 \x01(\v2\r.box.MetadataR\bMetadata\"D\n" +
	"\bMetadata\x128\n" +
	"\tTimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestampB\x06Z\x04./pbb\x06proto3"

var (
	file_stp_proto_rawDescOnce sync.Once
	file_stp_proto_rawDescData []byte
)

func file_stp_proto_rawDescGZIP() []byte {
	file_stp_proto_rawDescOnce.Do(func() {
		file_stp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stp_proto_rawDesc), len(file_stp_proto_rawDesc)))
	})
	return file_stp_proto_rawDescData
}

var file_stp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stp_proto_goTypes = []any{
	(*SignedTransport)(nil),       // 0: box.SignedTransport
	(*TransportContext)(nil),      // 1: box.TransportContext
	(*Introduce)(nil),             // 2: box.Introduce
	(*Handshake)(nil),             // 3: box.Handshake
	(*HandshakeOptions)(nil),      // 4: box.HandshakeOptions
	(*Conversation)(nil),          // 5: box.Conversation
	(*Metadata)(nil),              // 6: box.Metadata
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_stp_proto_depIdxs = []int32{
	1, // 0: box.SignedTransport.Context:type_name -> box.TransportContext
	4, // 1: box.Handshake.Opts:type_name -> box.HandshakeOptions
	6, // 2: box.Conversation.Metadata:type_name -> box.Metadata
	7, // 3: box.Metadata.Timestamp:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stp_proto_init() }
func file_stp_proto_init() {
	if File_stp_proto != nil {
		return
	}
	file_stp_proto_msgTypes[0].OneofWrappers = []any{}
	file_stp_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stp_proto_rawDesc), len(file_stp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stp_proto_goTypes,
		DependencyIndexes: file_stp_proto_depIdxs,
		MessageInfos:      file_stp_proto_msgTypes,
	}.Build()
	File_stp_proto = out.File
	file_stp_proto_goTypes = nil
	file_stp_proto_depIdxs = nil
}
